#!/bin/bash
EXTERNAL_FOLDER=$PWD
SRC_FOLDER=$EXTERNAL_FOLDER/src
TMP_FOLDER=/tmp/build/

mkdir -p $TMP_FOLDER
mkdir -p $SRC_FOLDER

NCPUS=$(grep -c ^processor /proc/cpuinfo)
BUILD_OPTS=-j$((NCPUS+1))

CLANG=$EXTERNAL_FOLDER/llvm/bin/clang
CLANGPP=$EXTERNAL_FOLDER/llvm/bin/clang++

CMAKE_PREFIX=$EXTERNAL_FOLDER/cmake
CMAKE=$CMAKE_PREFIX/bin/cmake
CMAKE_RELEASE_BUILD="-DCMAKE_BUILD_TYPE:STRING=Release"
CMAKE_USE_CLANG="-DCMAKE_CXX_COMPILER=${CLANGPP} -DCMAKE_C_COMPILER=${CLANG}"
BOOST_PREFIX=$EXTERNAL_FOLDER/boost

CLANG=$EXTERNAL_FOLDER/llvm/bin/clang
CLANGPP=$EXTERNAL_FOLDER/llvm/bin/clang++
CMAKE_RELEASE_BUILD="-DCMAKE_BUILD_TYPE:STRING=Release"
CMAKE_USE_CLANG="-DCMAKE_CXX_COMPILER=${CLANGPP} -DCMAKE_C_COMPILER=${CLANG}"

# LevelDB
LEVELDB_GIT=https://github.com/google/leveldb
LEVELDB_PREFIX=$EXTERNAL_FOLDER/leveldb

if [ ! -d $LEVELDB_PREFIX ]; then
    cd $EXTERNAL_FOLDER
    git clone $LEVELDB_GIT
fi

cd $LEVELDB_PREFIX
make clean
git pull
make CXX=$CLANGPP $BUILD_OPTS

# Google test
GTEST_FOLDER=$SRC_FOLDER/gtest
GTEST_SRC_FOLDER=$GTEST_FOLDER/build
GTEST_PREFIX=$EXTERNAL_FOLDER/gtest

cd $SRC_FOLDER
if [ ! -d $GTEST_FOLDER ]; then
    svn checkout http://googletest.googlecode.com/svn/trunk/ gtest
fi

cd $GTEST_FOLDER
svn update

rm -rf $GTEST_SRC_FOLDER
mkdir -p $GTEST_SRC_FOLDER
cd $GTEST_SRC_FOLDER
$CMAKE -DCMAKE_INSTALL_PREFIX:PATH=$GTEST_PREFIX -DCMAKE_BUILD_TYPE:STRING=Release -DBUILD_TESTING:BOOL=OFF $GTEST_FOLDER
make $BUILD_OPTS

# We need to install gtest manually.
rm -rf $GTEST_PREFIX
mkdir -p $GTEST_PREFIX
mkdir -p $GTEST_PREFIX/include
mkdir -p $GTEST_PREFIX/lib
cp -r $GTEST_FOLDER/include/gtest $GTEST_PREFIX/include
cp lib*.a $GTEST_PREFIX/lib/

# Google hash map
SPARSEHASH_LINK=http://sparsehash.googlecode.com/svn/trunk/
SPARSEHASH_FOLDER=$SRC_FOLDER/sparsehash
SPARSEHASH_PREFIX=$EXTERNAL_FOLDER/sparsehash

cd $SRC_FOLDER
echo $SPARSEHASH_FOLDER
echo $SPARSEHASH_LINK
if [ ! -d $SPARSEHASH_FOLDER ]; then
    svn checkout $SPARSEHASH_LINK sparsehash
    echo $SPARSEHASH_LINK
fi
cd $SPARSEHASH_FOLDER
svn update

./configure --prefix=$SPARSEHASH_PREFIX CXXFLAGS="-O4 -Wall"
make $BUILD_OPTS
make install

# Micro-benchmark
BENCHMARK_GIT=https://github.com/google/benchmark.git
BENCHMARK_SRC=$SRC_FOLDER/benchmark
BENCHMARK_BUILD=$TMP_FOLDER/benchmark
BENCHMARK_PREFIX=$EXTERNAL_FOLDER/benchmark

if [ ! -d $BENCHMARK_SRC ]; then
    cd $SRC_FOLDER
    git clone $BENCHMARK_GIT
fi

mkdir $BENCHMARK_BUILD
cd $BENCHMARK_BUILD
$CMAKE -DCMAKE_INSTALL_PREFIX:PATH=$BENCHMARK_PREFIX -DCMAKE_BUILD_TYPE:STRING=Release -DBUILD_TESTING:BOOL=OFF $CMAKE_USE_CLANG $BENCHMARK_SRC

# Require C++11 support.
make $BUILD_OPTS
rm -rf $BENCHMARK_BUILD
